frontier_explorer: BFS Class Reference
BFS Class Reference
Class to implement the BFS.
#include <BFS.hpp>
Public Member Functions
BFS (int, int)
Constructor for the class BFS.
std::queue< std::vector< int > > computeBFS (const std::queue< std::vector< int >> &, std::vector< int >)
function to compute BFS
void neighbourList (const std::vector< std::vector< int > > &, std::vector< int >, std::queue< std::vector< int > > &)
function to estimate the neighbouring node
int getExplored (int, int)
function to get the explored value of a specific grid
int getDistance (int, int)
function to get the distance value of a specific grid
~BFS ()
class destructor
Private Attributes
std::queue< std::vector< int > > pQueue
std::vector< std::vector< int > > distance
std::vector< std::vector< int > > explored
Detailed Description
Class to implement the BFS.
Parameters
pQueue queue to store the coordinates
distance euclidean distance from the start node
explored visited node in the occupancy grid
Returns
None
Definition at line 52 of file BFS.hpp.
Constructor & Destructor Documentation
BFS::BFS (int rows, int cols)
Constructor for the class BFS.
Parameters
cols column to resize the explored and distance
rows row to resize the explored and distance
Returns
None
Definition at line 47 of file BFS.cpp.
References distance, and explored.
BFS::~BFS ()
class destructor
Returns
None
Definition at line 148 of file BFS.cpp.
Member Function Documentation
std::queue< std::vector< int > > BFS::computeBFS (const std::queue< std::vector< int >> & , std::vector< int >)
function to compute BFS
Parameters
frontierQueue contains list of all frontiers
start point of the turtlebot
Returns
frontiers Queue to store all the frontiers
Definition at line 102 of file BFS.cpp.
References distance, explored, neighbourList(), and pQueue.
Referenced by map::frontierSearch(), and TEST().
int BFS::getDistance (int x, int y)
function to get the distance value of a specific grid
Parameters
x x-position of the grid
y y-position of the grid
Returns
integer value of distance grid for the x and y coordinates
Definition at line 71 of file BFS.cpp.
References distance.
Referenced by TEST().
int BFS::getExplored (int x, int y)
function to get the explored value of a specific grid
Parameters
x x-position of the grid
y y-position of the grid
Returns
integer value of explored grid for the x and y coordinates
Definition at line 66 of file BFS.cpp.
References explored.
Referenced by TEST().
void BFS::neighbourList (const std::vector< std::vector< int > > & , std::vector< int > , std::queue< std::vector< int > > &)
function to estimate the neighbouring node
Parameters
frontier vector
vector coordinate to which neighbouring node has to found out
list of all neighbouring node of the given coordinate
Returns
frontiers Queue to store all the frontiers
Definition at line 76 of file BFS.cpp.
Referenced by computeBFS(), and TEST().
Member Data Documentation
std::vector<std::vector<int> > BFS::distance private
Definition at line 57 of file BFS.hpp.
Referenced by BFS(), computeBFS(), and getDistance().
std::vector<std::vector<int> > BFS::explored private
Definition at line 59 of file BFS.hpp.
Referenced by BFS(), computeBFS(), and getExplored().
std::queue<std::vector<int> > BFS::pQueue private
Definition at line 55 of file BFS.hpp.
Referenced by computeBFS().
The documentation for this class was generated from the following files:
include/BFS.hpp
src/BFS.cpp