frontier_explorer: sensor Class Reference
sensor Class Reference
Class to implement the radiation sensor.
#include <sensor.hpp>
Public Member Functions
sensor (map &)
class constructor
void saveRadiationMap ()
Class to save the radiation data as ppm file.
std::vector< std::vector< float > > getRadiationMap ()
Class to implement the BFS.
~sensor ()
Private Attributes
std::vector< std::vector< float > > radiationMap
Detailed Description
Class to implement the radiation sensor.
Parameters
radiationMap that store the intensity of the radiation
Returns
None
Definition at line 53 of file sensor.hpp.
Constructor & Destructor Documentation
sensor::sensor (map & obj) explicit
class constructor
Parameters
Map object to get number of rows and column in the map
Returns
None
Definition at line 47 of file sensor.cpp.
References radiationMap, map::returnCols(), and map::returnRows().
sensor::~sensor ()
Definition at line 90 of file sensor.cpp.
Member Function Documentation
std::vector< std::vector< float > > sensor::getRadiationMap ()
Class to implement the BFS.
Returns
radiationMap in 2-D vector
Definition at line 86 of file sensor.cpp.
References radiationMap.
Referenced by TEST().
void sensor::saveRadiationMap ()
Class to save the radiation data as ppm file.
Returns
None
Definition at line 65 of file sensor.cpp.
References radiationMap.
Referenced by main().
Member Data Documentation
std::vector<std::vector<float> > sensor::radiationMap private
Definition at line 56 of file sensor.hpp.
Referenced by getRadiationMap(), saveRadiationMap(), and sensor().
The documentation for this class was generated from the following files:
include/sensor.hpp
src/sensor.cpp