frontier_explorer: explore Class Reference
explore Class Reference
Class to implement the BFS.
#include <explore.hpp>
Public Member Functions
explore ()
class constructor
void pathSearch (std::vector< int >, std::vector< int >, map &)
pathSearch to find the path to the goal
bool computeShortestPath (std::vector< int >, std::vector< int >, std::vector< std::vector< int > > &, map &)
function to compute the shortest path using BFS
void findObstacleFreeNeighbours (std::vector< int >, std::queue< std::vector< int > > &, map &)
function to find the neighbour of the given point which is without the obstacle
bool navigate (float, map &, std::vector< int >)
function to publish goal to the move base topic
~explore ()
class destructor
Private Attributes
std::vector< std::vector< int > > path
Detailed Description
Class to implement the BFS.
Parameters
path vector to store the path
Returns
None
Definition at line 54 of file explore.hpp.
Constructor & Destructor Documentation
explore::explore ()
class constructor
Returns
None
Definition at line 51 of file explore.cpp.
explore::~explore ()
class destructor
Returns
None
Definition at line 250 of file explore.cpp.
Member Function Documentation
bool explore::computeShortestPath (std::vector< int > start, std::vector< int > End, std::vector< std::vector< int > > & path1, map & obj)
function to compute the shortest path using BFS
Parameters
start vector contains the start point for the path
end vector contains the end point for the path
path that stores the path to the goal
map Object to get the rows, grid value and column
Returns
bool
Definition at line 83 of file explore.cpp.
References findObstacleFreeNeighbours(), path, map::returnCols(), and map::returnRows().
Referenced by pathSearch(), and TEST().
void explore::findObstacleFreeNeighbours (std::vector< int > v, std::queue< std::vector< int > > & list, map & obj)
function to find the neighbour of the given point which is without the obstacle
Parameters
v vector contains the point to which neighbour has to be found
list is a queue contains the list of neighbour
map Object to get rows and columns
Returns
None
Definition at line 54 of file explore.cpp.
References map::getGridValue(), map::returnCols(), and map::returnRows().
Referenced by computeShortestPath(), and TEST().
bool explore::navigate (float resolution, map & obj, std::vector< int > pos)
function to publish goal to the move base topic
Parameters
resolution is a float that contains the resolution of the map
map Object to get the rows, column
Returns
bool whether it has reached the target or not
Definition at line 165 of file explore.cpp.
References path, map::returnCols(), and map::returnRows().
Referenced by main().
void explore::pathSearch (std::vector< int > start, std::vector< int > end, map & obj)
pathSearch to find the path to the goal
Parameters
start contains the start point for the path
end contains the end point for the path
map object to get rows and columns
Returns
None
Definition at line 155 of file explore.cpp.
References computeShortestPath(), and path.
Referenced by main().
Member Data Documentation
std::vector<std::vector<int> > explore::path private
Definition at line 57 of file explore.hpp.
Referenced by computeShortestPath(), navigate(), and pathSearch().
The documentation for this class was generated from the following files:
include/explore.hpp
src/explore.cpp