frontier_explorer: map Class Reference
map Class Reference
Class to implement the MAP.
#include <map.hpp>
Public Member Functions
map ()
Constructor for the class map.
void frontierSearch (int, int)
Function to search frontiers in the map.
bool checkNeighbour (int, int, int)
Function to check if the neighbour's grid value.
std::vector< int > computeFrontierCentroid (const std::queue< std::vector< int >> &)
Function to compute the centroid of the frontier.
std::vector< int > nearest (const std::queue< std::vector< int >> &, int, int)
Function to find the point closest to computed centroid.
bool requestMap (ros::NodeHandle &)
Function to request map from gmapping node.
void mapcallback (const nav_msgs::OccupancyGrid &msg)
CallBack function for the map subscriber.
std::vector< int > nearestCentroid (int, int)
Function to find the point closest to computed centroid.
int getGridValue (int, int)
Function to return the grid value.
int getCentroidSize ()
Function to return the size of centroid queue.
int returnRows ()
Function to return row size.
int returnCols ()
Function to return coloumn size.
float getResolution ()
Function to return resolution of the map.
std::vector< int > getStart ()
Function to return origin.
~map ()
Destructor for the class map.
Public Attributes
std::vector< int > start
Private Attributes
std::queue< std::vector< int > > frontierQueue
std::queue< std::vector< int > > centroidQueue
std::queue< std::vector< int > > explored
std::vector< std::vector< int > > grid
int rows
int cols
float mapResolution
ros::Subscriber OGM_subscriber
Detailed Description
Class to implement the MAP.
Parameters
frontier queue to hold the frontier points
Centroid queue to hold the centroid of individual frontiers
grid the map as 2d vector
row integer with row size of grid
cols integer with coloumn size of grid
mapResolution integer with resolution of grid
OGM_Subscriber is the subscriber handle for /Map
start vector containing the origin
Returns
none
Definition at line 63 of file map.hpp.
Constructor & Destructor Documentation
map::map ()
Constructor for the class map.
Parameters
None
Returns
None
Definition at line 51 of file map.cpp.
References cols, grid, mapResolution, and rows.
Referenced by frontierSearch().
map::~map ()
Destructor for the class map.
Parameters
None
Returns
None
Definition at line 284 of file map.cpp.
Member Function Documentation
bool map::checkNeighbour (int xPoint, int yPoint, int mode)
Function to check if the neighbour's grid value.
Parameters
X coordinate of grid
Y coordinate of grid
Value to be checked
Returns
Check
Definition at line 124 of file map.cpp.
References grid.
Referenced by frontierSearch(), and TEST().
std::vector< int > map::computeFrontierCentroid (const std::queue< std::vector< int >> & q)
Function to compute the centroid of the frontier.
Parameters
Frontier Queue containing the centroid coordinates
Returns
Centroid point
Definition at line 173 of file map.cpp.
References nearest().
Referenced by frontierSearch(), and TEST().
void map::frontierSearch (int height, int width)
Function to search frontiers in the map.
Parameters
X coordinate of grid
Y coordinate of grid
Returns
none
Definition at line 195 of file map.cpp.
References centroidQueue, checkNeighbour(), BFS::computeBFS(), computeFrontierCentroid(), explored, frontierQueue, grid, and map().
Referenced by main(), and TEST().
int map::getCentroidSize ()
Function to return the size of centroid queue.
Parameters
None
Returns
centroid size
Definition at line 120 of file map.cpp.
References centroidQueue.
Referenced by TEST().
int map::getGridValue (int x, int y)
Function to return the grid value.
Parameters
X coordinate
Y coordinate
Returns
Grid value
Definition at line 108 of file map.cpp.
References grid.
Referenced by explore::findObstacleFreeNeighbours(), and TEST().
float map::getResolution ()
Function to return resolution of the map.
Parameters
None
Returns
resolution of the map
Definition at line 280 of file map.cpp.
References mapResolution.
Referenced by main(), and TEST().
std::vector< int > map::getStart ()
Function to return origin.
Parameters
None
Returns
origin vector
Definition at line 276 of file map.cpp.
References start.
Referenced by main().
void map::mapcallback (const nav_msgs::OccupancyGrid & msg)
CallBack function for the map subscriber.
Parameters
Contains the map in as occupancy grid in row major form
Returns
none
Definition at line 76 of file map.cpp.
References cols, grid, mapResolution, rows, and start.
Referenced by requestMap().
std::vector< int > map::nearest (const std::queue< std::vector< int >> & q, int centroidx, int centroidy)
Function to find the point closest to computed centroid.
Parameters
Frontier Queue containing individual frontier points
Returns
Point on frontier nearest to centroid
Definition at line 148 of file map.cpp.
Referenced by computeFrontierCentroid(), and TEST().
std::vector< int > map::nearestCentroid (int startX, int startY)
Function to find the point closest to computed centroid.
Parameters
Frontier Queue containing individual frontier points
Returns
Point on frontier nearest to centroid
Definition at line 248 of file map.cpp.
References centroidQueue.
Referenced by main().
bool map::requestMap (ros::NodeHandle & nh)
Function to request map from gmapping node.
Parameters
Node handle
Returns
Check if map is received
Definition at line 70 of file map.cpp.
References mapcallback(), and OGM_subscriber.
Referenced by main(), and TEST().
int map::returnCols ()
Function to return coloumn size.
Parameters
None
Returns
coloumn size
Definition at line 116 of file map.cpp.
References cols.
Referenced by explore::computeShortestPath(), explore::findObstacleFreeNeighbours(), main(), explore::navigate(), sensor::sensor(), and TEST().
int map::returnRows ()
Function to return row size.
Parameters
None
Returns
row size
Definition at line 112 of file map.cpp.
References rows.
Referenced by explore::computeShortestPath(), explore::findObstacleFreeNeighbours(), main(), explore::navigate(), sensor::sensor(), and TEST().
Member Data Documentation
std::queue<std::vector<int> > map::centroidQueue private
Definition at line 66 of file map.hpp.
Referenced by frontierSearch(), getCentroidSize(), and nearestCentroid().
int map::cols private
Definition at line 69 of file map.hpp.
Referenced by map(), mapcallback(), and returnCols().
std::queue<std::vector<int> > map::explored private
Definition at line 67 of file map.hpp.
Referenced by frontierSearch().
std::queue<std::vector<int> > map::frontierQueue private
Definition at line 65 of file map.hpp.
Referenced by frontierSearch().
std::vector<std::vector<int> > map::grid private
Definition at line 68 of file map.hpp.
Referenced by checkNeighbour(), frontierSearch(), getGridValue(), map(), and mapcallback().
float map::mapResolution private
Definition at line 70 of file map.hpp.
Referenced by getResolution(), map(), and mapcallback().
ros::Subscriber map::OGM_subscriber private
Definition at line 71 of file map.hpp.
Referenced by requestMap().
int map::rows private
Definition at line 69 of file map.hpp.
Referenced by map(), mapcallback(), and returnRows().
std::vector<int> map::start
Definition at line 81 of file map.hpp.
Referenced by getStart(), and mapcallback().
The documentation for this class was generated from the following files:
include/map.hpp
src/map.cpp