frontier_explorer: test/testBFS.cpp File Reference
testBFS.cpp File Reference
#include <gtest/gtest.h>
#include <ros/ros.h>
#include <ros/service_client.h>
#include <vector>
#include <queue>
#include "../include/BFS.hpp"
Functions
TEST (computeBFS, checkBFSAlogrithm)
TEST (NeighbourList, checkNeighbourListOutput)
TEST (getExplored, checkReturnValue)
TEST (getDistance, checkReturnValue)
Function Documentation
TEST (computeBFS , checkBFSAlogrithm)
Definition at line 49 of file testBFS.cpp.
References BFS::computeBFS().
TEST (NeighbourList , checkNeighbourListOutput)
Definition at line 80 of file testBFS.cpp.
References BFS::neighbourList().
TEST (getExplored , checkReturnValue)
Definition at line 114 of file testBFS.cpp.
References BFS::getExplored().
TEST (getDistance , checkReturnValue)
Definition at line 119 of file testBFS.cpp.
References BFS::getDistance().