frontier_explorer: test/testMapGen.cpp File Reference
testMapGen.cpp File Reference
To test the class mapGen.
#include <gtest/gtest.h>
#include <ros/ros.h>
#include <ros/service_client.h>
#include "map.hpp"
#include "BFS.hpp"
Functions
TEST (requestMap, checkNodeActivation)
TEST (frontierSearch, CheckFrontierSearch)
TEST (checkNeighbour, CheckFrontierSearch)
TEST (GetResolution, CheckResolution)
TEST (nearest, checkReturnValue)
TEST (computeFrontierCentroid, checkCentroidValue)
TEST (ReturnRows, checkReturnValueOfRow)
TEST (ReturnCols, checkReturnValueOfCols)
TEST (GetGridValue, checkGetGridValue)
Detailed Description
To test the class mapGen.
BSD 3-Clause License
Copyright (c) 2018, Nantha Kumar Sunder, Nithish Sanjeev Kumar All rights reserved.
Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:
Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.
Neither the name of the copyright holder nor the names of its contributors may be used to endorse or promote products derived from this software without specific prior written permission.
THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
Nithish Sanjeev Kumar Nantha Kumar Sunder
Copyright
2018 , Nantha Kumar Sunder, Nithish Sanjeev Kumar All rights reserved
Definition in file testMapGen.cpp.
Function Documentation
TEST (requestMap , checkNodeActivation)
Definition at line 49 of file testMapGen.cpp.
References map::requestMap().
TEST (frontierSearch , CheckFrontierSearch)
Definition at line 64 of file testMapGen.cpp.
References map::frontierSearch(), and map::getCentroidSize().
TEST (checkNeighbour , CheckFrontierSearch)
Definition at line 74 of file testMapGen.cpp.
References map::checkNeighbour().
TEST (GetResolution , CheckResolution)
Definition at line 79 of file testMapGen.cpp.
References map::getResolution().
TEST (nearest , checkReturnValue)
Definition at line 84 of file testMapGen.cpp.
References map::nearest().
TEST (computeFrontierCentroid , checkCentroidValue)
Definition at line 110 of file testMapGen.cpp.
References map::computeFrontierCentroid().
TEST (ReturnRows , checkReturnValueOfRow)
Definition at line 134 of file testMapGen.cpp.
References map::returnRows().
TEST (ReturnCols , checkReturnValueOfCols)
Definition at line 138 of file testMapGen.cpp.
References map::returnCols().
TEST (GetGridValue , checkGetGridValue)
Definition at line 142 of file testMapGen.cpp.
References map::getGridValue().